import sys, os
sys.path.append(os.getcwd())

import numpy as np

print("=" * 80)
print("DenseHOGraspNet vs DexGraspNet 스케일 비교")
print("=" * 80)

print("\n[DenseHOGraspNet 분석 결과]")
print("-" * 80)
print("Object PC Scales:")
print("  - 범위: 10.315496 ~ 10.396067")
print("  - 평균: 10.360308 ± 0.018999")
print("  - 중앙값: 10.360917")
print("  - 변동: 매우 일정 (Std = 0.018999)")
print("\nHand PC Scales:")
print("  - 범위: 11.796265 ~ 16.002655")
print("  - 평균: 14.317524 ± 0.828064")
print("  - 중앙값: 14.469578")
print("  - 변동: 중간 수준 (Std = 0.828064)")
print("  - 범위의 크기: 약 4.2 (16.0 - 11.8)")
print("\n특이점:")
print("  - 모든 163개 샘플이 10~16 범위의 큰 스케일을 가짐")
print("  - Hand는 Object에 비해 약 1.4배 더 큼")
print("  - Hand의 스케일이 손 포즈/포지션에 따라 다양함")

print("\n" + "=" * 80)
print("예상되는 원인:")
print("=" * 80)
print("1. DenseHOGraspNet은 생 센서 데이터로 보임 (밀리미터 단위?)")
print("   - 좌표값이 절대적으로 큼 (10~16)")
print("   - 정규화되지 않음")
print("\n2. Hand PC의 높은 변동성:")
print("   - 다양한 포즈에서 손의 크기/높이가 다름")
print("   - 손가락 펼침 정도의 차이")
print("   - 카메라 각도/거리 변화")
print("\n3. DexGraspNet과의 비교 (제프트의 수행 언급 -2~2):")
print("   - DexGraspNet: 정규화된 좌표 (-1 ~ 1 또는 -2 ~ 2)")
print("   - DenseHOGraspNet: 정규화되지 않은 절대 좌표 (10~16)")
print("   - 이는 근본적으로 다른 데이터 전처리 방식")

print("\n" + "=" * 80)
print("권장사항:")
print("=" * 80)
print("1. DenseHOGraspNet을 정규화해야 함:")
print("   - 각 샘플별로 Mean을 빼고 Std로 나누기")
print("   - 또는 Min-Max 정규화")
print("\n2. Hand와 Object를 분리 정규화 고려:")
print("   - Hand의 변동성이 크므로 별도 처리 가능")
print("\n3. 학습 전 반드시 확인:")
print("   - 정규화된 좌표 범위 (-1 ~ 1 또는 -2 ~ 2)")
print("   - 스케일 일관성")
